### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by dzogrim** [JohannesEbke/aws_list_all#3]
Hi, trying to run the command to show all resources but the script goes out of memory.
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
[...]
	File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
MemoryError
```
How much memory is required to "query" everything and how it could be optimized? Thanks a lot.

**Comment by JohannesEbke** [comment]
Hi @dzogrim, a query on all services and all regions runs up to 3.5GB of RAM for me, if I limit it to one region, it's just 600M, so that is a workaround you could try. If you sequence the regions, you can still get a full listing.

However, randomizing the queries across regions and services is the key to make aws-list-all fast (since it avoids rate limiting). 3.6GB still seems a bit much, a bit of profiling could probably help, but since there is a workaround it's not a priority for me at the moment.

**Comment by dzogrim** [comment]
OK, thanks... I had much RAM errors with a 8 GB virtual machine. It's actually fine with another hardware and more memory.
